# Cumulative Effects Assessment {#ceasection}

The cumulative effects assessment (CEA) is rooted in natural resource management and environmental impact assessment processes [@halpern2013] and has appeared in the legislation in certain countries for decades, including the United States (National Environmental Policy Act 40 CFR \S 1508.7, 1969), Canada (Canadian Environmental Assessment Act S.C. 1992, c. 37, now the [Impact Assessment Act 2019](https://laws-lois.justice.gc.ca/eng/acts/i-2.75/FullText.html) 22 (1)(a)(ii)), Australia, and various European countries [@halpern2013]. The scientific and grey[^grey] literature thus abounds with publications providing definitions, implementation frameworks, best practices guides, and guiding principles for cumulative effects assessments in environmental impact assessments [*e.g.* @peterson1987; @hegmann1999; @krausman2011]. Therefore, a wide variety of definitions and approaches exists [see @therivel2007; @duinker2013].

In its broadest sense, the Canadian Council of Ministers of the Environment [@conseilcanadiendesministresdelenvironnement2014] defines cumulative effects as a “change in the environment caused by multiple interactions among human activities and natural processes that accumulate across space and time.”* Cumulative effects assessment is defined as “a systematic process of identifying, analyzing and evaluating cumulative effects”*.

These definitions point to the systematic nature of cumulative effects and their assessment, i.e., management of ecosystems and the interactions that structure them as a whole, including human aspects, as related to ecosystem-based management [@christensen1996; @rosenberg2005; @leslie2007]. However, cumulative effects are defined in more restrictive terms in policy, legislative, and regulatory texts [@jones2016]. The 1992 Canadian Environmental Assessment Act defines cumulative effects as follows:

> *“[...] the cumulative environmental effects [of a project] that are likely to result from the project in combination with other projects or activities”*.

Cumulative effects assessment processes are thus typically conducted from a project perspective rather than a systemic perspective. A number of scientists thus call for the use of regional approaches to the cumulative effects assessment [*e.g.* @dube2003; @duinker2006; @jones2016; @sinclair2017]. Moreover, Canada’s Minister of the Environment and Climate Change recently authorized a [regional assessment of the St. Lawrence River area](https://iaac-aeic.gc.ca/050/evaluations/document/140637?&culture=en-CA) on July 15, 2021, in response to a [request by the Mohawk Nation of Kahnawà:ke](https://iaac-aeic.gc.ca/050/documents/p80913/135682E.pdf) under the [*Impact Assessment Act*](https://laws-lois.justice.gc.ca/eng/acts/i-2.75/FullText.html). According to @sinclair2017, a regional cumulative effects assessment can be defined as follows:

> *”[A Regional Effects Assessment (REA)] is an [environmental assessment] whose primary or sole defining feature is its regional scope and its focus on understanding the interactions between human activities and the natural world. This means that in just about all aspects other than its spatial limitations, an REA should be comprehensive and integrated.”*

Similar to a project-based approach within environmental impact assessments, the regional approach focuses instead on the total effects (*effect-based*) and viability of environmental receptors of interest, commonly referred to as valued components [@beanlands1983; @sinclair2017]. Several constraints limit its practical application, especially the need to use environmental measures -- *e.g.* variation in the mortality rate of a species as a function of an environmental stressor -- to establish the effects of one or more stressors on a valued component. These types of measures are particularly difficult to obtain in cumulative effects assessments; they also necessarily make assessments reactive since effects must be observed in order to establish a meaningful link between the presence of a stressor and the degradation of a valued component [@dube2003]. An ideal approach would instead make it possible to combine effects-based and stressor-based cumulative effects assessment approaches [@dube2003; @sinclair2017].