# eDrivers {#eDrivers}

Along with a description of the distribution and intensity of environmental drivers in the St. Lawrence System, @beauchesne2020 launched an open knowledge platform called [*eDrivers*](https://david-beauchesne.shinyapps.io/edriversapp_dev/). This project seeked to shared knowledge on environmental drivers as well as to gather a community of experts whose goal is to structure, standardize and share knowledge on drivers in support of science and maangement. This initiative also sought to uphold the highest standards of data management and open science and was built on 4 guiding principles: 

1. Unity and Inclusiveness
2. Findability, Accessibility, Interoperability, and Reusability
3. Adaptiveness
4. Recognition

As part of this assessment, we updated *eDrivers* to include the environmental drivers that were identified on the Scotian Shelf. For more details on *eDrivers*, you may visit the [web application](https://david-beauchesne.shinyapps.io/edriversapp_dev/) and refer to @beauchesne2020.


```{r edrivers, out.width = "100%"}
knitr::include_app(
  "https://david-beauchesne.shinyapps.io/edriversapp/",
  height = "900px"
)
```

