# Cumulative Effects Assessment {#ceasection}

The cumulative effects assessment (CEA) framework stems from natural resource management and environmental impact assessment regulatory processes [@halpern2013]. CEA has been part of environmental legislation for decades in certain countries, including the United States (National Environmental Policy Act 40 CFR \S 1508.7, 1969), Canada (Canadian Environmental Assessment Act S.C. 1992, c. 37, now the [Impact Assessment Act 2019](https://laws-lois.justice.gc.ca/eng/acts/i-2.75/FullText.html) 22 (1)(a)(ii)), Australia, and various European countries [@halpern2013]. There is therefore a rich literature providing various definitions, guiding principles for assessments and best practice guides for assessment approaches [*e.g.* @peterson1987; @hegmann1999; @therivel2007; @krausman2011; @duinker2013].

The Canadian Council of Ministers of the Environment [@conseilcanadiendesministresdelenvironnement2014] defines cumulative effects as *"changes in the environment caused by multiple interactions among human activities and natural processes that accumulate across space and time."* Cumulative effects assessment is defined as *"a systematic process of identifying, analyzing and evaluating cumulative effects"*. These definitions hint at the systems view of cumulative effects assessment and how it relates to an ecosystem-based management approach focusing on the structure of ecosystems as a whole [@christensen1996; @rosenberg2005; @leslie2007]. 

From a policy, legislative, and regulatory standpoint, however, cumulative effects are defined more narrowly [@jones2016]. The 1992 Canadian Environmental Assessment Act defines cumulative effects as follows:

> *“[...] the cumulative environmental effects [of a project] that are likely to result from the project in combination with other projects or activities”*.

Assessments are thus usually undertaken at the scale of individual projects rather than through a systematic lens. Regional and systematic approaches to cumulative effects assessments are however gaining support [*e.g.* @dube2003; @duinker2006; @jones2016; @sinclair2017]. According to @sinclair2017, a regional cumulative effects assessment can be defined as follows:

> *”[A Regional Effects Assessment (REA)] is an [environmental assessment] whose primary or sole defining feature is its regional scope and its focus on understanding the interactions between human activities and the natural world. This means that in just about all aspects other than its spatial limitations, an REA should be comprehensive and integrated.”*

Regional approaches focus on the total effects and viability of environmental receptors of interest, commonly referred to as valued components [@beanlands1983; @sinclair2017]. Several constraints limit its practical application, especially access to quality data to establish the effects of one or more stressors on a valued component. These types of measures are particularly difficult to obtain in cumulative effects assessments. A study by @halpern2008a took a major step toward an ecosystem-based perspective to cumulative effects assessment. In their work, @halpern2008a evaluated the cumulative effects of 17 environmental stressors on 20 types of marine ecosystems and showed that few environments remain free of environmental pressures. Updates published in 2015 [@halpern2015a] and 2019 [@halpern2019] also show general increases in cumulative effects across the global oceans. In addition to being used worldwide, this method has been used many times in different regions of the globe to characterize cumulative effects, including in California [@halpern2009], the Arctic [@andersen2015; @afflerbach2017], and the Canadian Pacific Ocean [@ban2010; @clarkemurray2015; @clarkemurray2015a; @singh2020]. 

Recently, @beauchesne2020c expanded on the work of @halpern2008a to develop a new approach to assess cumulative effects on species that explicitly considers the underlying web of interactions structuring communities. This work built on the ecological understanding that environmental pressures indirectly propagate through ecological communities by way of species interactions [@estes1974; @paine1980; @wootton2002; @bascompte2009a; @estes2011], *i.e* species cannot be considered in a vacuum [@tylianakis2008; @ogorman2009; @gilarranz2016; @gilarranz2017; @ogorman2019; @waller2020; @beauchesne2021]. @beauchesne2020c used this approach to perform a cumulative effects assessment of global changes on the food webs of the St. Lawrence System in eastern Canada. They uncovered cumulative effects to species that would otherwise have been overlooked had species interactions been ignored, especially for fishes and marine mammals. 

The approaches developed by @halpern2008a and @beauchesne2020c form the basis of the work presented in the current assessment. In the remainder of this report, we refer to the approach developed by @halpern2008a as a [species-scale cumulative effects assessment](#speciesmethod), while that of @beauchesne2020c is referred to as a [network-scale cumulative effects assessment](@networkmethod). Both approaches are presented and applied to perform a cumulative effects assessment of global changes on the food webs of the Scotian Shelf bioregion. 



