## Metaweb {#metamodule}

We predicted the metaweb of the Scotian Shelf, *i.e.* the network of biotic interactions, using a recommender approach [@beauchesne2016]. Here, we provide a brief overview of the approach, but refer to @beauchesne2016 for more details. The approach is built on a series of logical steps that predict a candidate resource list for each taxon considered based on empirically observed interactions and on the similarity between consumers and resources. It predicts pairwise interactions given taxonomic and dietary similarity between taxa using the K-nearest neighbor algorithm [KNN; @murphy2012]. 

Predictions are informed by a catalogue of empirical interactions from all over the world [@beauchesne2016]. The interactions catalogue was built using food web data [@brose2005; @kortsch2015; @universityofcanberra2016], predator-prey interactions [@barnes2008] and pairwise interactions from the GloBI database [@poelen2014; @poelen2019]. We limited the compendium to taxa found in marine and coastal ecosystems. The original interaction catalogue was built for a cumulative effects assessment of global changes on the food web of the St. Lawrence System [@beauchesne2020c]. The interaction catalogue was updated for the assessment of the Scotian Shelf using the GloBI database. We used the taxonomic families from the list of species considered for the assessment to identify all member species of those families for which interactions were available on the GloBI dataset using the `rglobi` package [@poelen2019]. We then combined the original interaction catalogue with the interactions extracted from GloBI to form a new catalogue of biotic interactions. This process yielded a total of 183 625 pairwise interactions between 14 870 taxa to inform interaction predictions. 

Taxa similarity was evaluated from taxonomic classification and sets of consumers or resources using the Tanimoto similarity measure ($T$), which compares two vectors $x$ and $y$ with $n = \left\vert x \right\vert = \left\vert y \right\vert$ elements, and is defined as the size of the intersection of two sets divided by their union:


$$T_{x,y} = \frac{\left \vert x \cap y \right \vert}{\left \vert x \cup y \right \vert}$$

where $\cap$ is the intersect and $\cup$ the union of the vectors. Adding a weighting scheme, we can measure the similarity using two different sets of vectors $\{x,y\}$ and $\{u,v\}$: 

$$T_{x,y,u,v,w_t} = w_t T_{x,y} + (1-w_t) T_{u,v}$$

A weight of 0.5 was given to taxonomy and consumers or resources to consider them simultaneously [@desjardins-proulx2016]. The taxonomy of all taxa considered was accessed and validated from WoRMS [@wormseditorialboard2017] using the `taxize` package [@chamberlain2013; @chamberlain2019]. We included the main phytoplankton and zooplankton taxa found in the St. Lawrence System to predict the metaweb [@morissette2003; @savenkoff2004; @savenkoff2012]; we then grouped predictions under phytoplankton or zooplankton. 

This yielded a total of 772 taxa ($S$) for which we predicted a metaweb structured by 18 021 links ($L$), a link density ($L_{moy} = L/S$) of 23.34 and a connectance ($C = L/S^2$) of 0.03, which is within range of most reported food webs [@dunne2002a].
 
 
