## Trophic sensitivity {#trsmodule}

The approach used to evaluate trophic sensitivity comes from @beauchesne2020c and @beauchesne2021. Here, we provide a brief description of the approach; a full description is available in those works. @beauchesne2021 developed a theoretical framework to evaluate a species' sensitivity to multiple stressors as a function of its trophic position, which we refer to as a species' trophic sensitivity. @beauchesne2021 simulated stressors on the most empirically abundant 3-species motifs --- *i.e.* tri-trophic food chain, omnivory, exploitative competition and apparent competition -- using Lotka-Volterra models [@gellner2016]. Negative effects of environmental pressures were simulated using combinations of equilibria equation parameters for resource growth, mortality, attack and conversion rates; these represent effects to ecological processes and their combination are the pathways through which environmental drivers affect species directly and indirectly through their ecological interactions. All possible pathways of effects -- *i.e.* all combinations of ecological processes -- were simulated for each 3-species motif considered. The difference between equilibrium population abundance before and after simulations was used as a proxy of a species' trophic sensitivity; This represents the net effects of stressors on species and integrates all direct effects to a species, and all indirect effects propagating through its interactions with other species [@abrams1996; @beauchesne2021].

To evaluate a species' trophic sensitivity empirically, @beauchesne2020 used simulation results from @beauchesne2021 as heuristics to infer a species' anticipated trophic sensitivity to the effects of environmental drivers as a function its position in the ecological network of the Scotian Shelf. @beauchesne2020 used the absolute values of simulated trophic sensitivities and considered that any effect to a species' population dynamics, whether negative or positive, can propagate and disturb the dynamics of an ecological community. Pathways of effect were also simplified to consider only effects to population density for ease of evaluation empirically, as effects to ecological processes such as attack and conversion rates are inherently challenging to evaluate empirically, especially for many species simultaneously. Simplified pathways were then averaged to obtain a single value of trophic sensitivity per pathway of effect. This resulted in 124 possible trophic sensitivity values based on the position and types of ecological interactions in which a species is involved. All trophic sensitivities were scaled between 0 and 1 for the analyses. Refer to @beauchesne2020c and @beauchesne2021 for more details, and to the description of the [network-scale assessment model](#networkmethod) for a description of how trophic sensitivity values are used in the assessment of the cumulative effects of global changes on the food webs of the Scotian Shelf. 
