# Perspectives {#perspectives}

The proposed assessment provides a first look at the direct and indirect effects of global changes on the ecological communities of the Scotian Shelf Bioregion. Some limits and perspectives were already discussed in the [Methods](#method) and [Modules](#modules). Here, we discuss some additional perspectives of the proposed assessment. 

## Data modules {.unlisted .unnumbered}

Much of the limitations and assumptions related to the approaches proposed by @halpern2008a and @beauchesne2020c are representative of a general lack of knowledge and data for the application of holistic environmental approaches. We refer to these as knowledge limitations rather than methodological limitations. That is not to say that the methods have no limits; rather, it is differentiating the limits associated with the data used to that of the approaches themselves. In terms of data use, the approaches proposed by @halpern2008a and @beauchesne2020c are highly flexible and provide the ability to use a wide variety of data. As stated in the [methods](#methods) section, both approaches rely on a series of data modules that characterize an area of interest: 1) the [distribution of species](#spmodule) for this particular assessment, 2) the spatial distribution and relative intensity of the [environmental drivers](#drmodule), 3) the [species-specific sensitivity](sssmodule) of each species to each driver, 4) the [metaweb](#metamodule) of species interactions, and 5) the [trophic sensitivity](#trsmodule) of species to trophically-mediated indirect effects. These individual modules are flexible, grounded in theory and data-oriented; the expanding corpus of openly available environmental knowledge and computational capabilities can thus be leveraged to independently and incrementally improve their quality and, in doing so, enhance the quality of cumulative effects assessments and other ecosystem-based assessments such as marine spatial planning. Those modules are also greatly discussed in the scientific literature and new approaches are regularly published. It thus seems reasonable to expect that the quality of the data and methods available to prepare the data modules necessary for the cumulative effects assessment will keep improving through time. Each data module could thus be updated and improved as better information becomes available. 


## Cumulative effects of global changes on habitats {.unlisted .unnumbered}

A parallel assessment was performed on habitats of the Scotian Shelf using the @halpern2008a approach by a team led by Noreen Kelly from the Department of Fisheries and Oceans's Bedford Institute of Oceanography. This assessment is almost completed and a comparison of both assessments would be interesting scientifically and from a management standpoint. Our teams have already exchanged and a qualitative overview of our results reveals that both assessments identify similar areas of greater cumulative risk on the Scotian Shelf Bioregion. A more in-depth comparison of both assessments would however be highly valuable. Steps could also be taken to combine both assessments together into a meta-assessments that considers both habitat and species together. 

 
## Operationalizing cumulative effects assessments {.unlisted .unnumbered}

Cumulative effects assessments rely on a significant amount of data, which is frequently cited as their major limitation [*e.g.* @jones2016; @hodgson2019]. The necessary data or knowledge is sometimes unavailable, inaccessible, or non-existent. Even when available, data can be particularly challenging to assemble into a database that can be used to conduct large-scale, holistic assessments. These growing data needs highlight the need to leverage acquired knowledge, structure it in an interoperable way -- *i.e.* make it easier to connect separate databases -- make them available to all, and build infrastructures that maximize our adaptive management capabilities [@reichman2011; @poisot2013; @wilkinson2016; @williams2020b]. The reproducibility tools presented in section \@ref(nceadfo) of this assessment offer a major step towards achieving such capabilities. The `nceadfo` research compendium and the `pipedat` R package could be leveraged to update the current assessment very efficiently and/or to expand the assessment to other areas of interest. For instance, the assessment performed for the St. Lawrence System [@beauchesne2020c] could be combined with the assessment of the Scotian Shelf Bioregion. The current assessment could also be leveraged to expand the assessment to the Newfoundland and Labrador Bioregion in order to obtain a large-scale overview of cumulative effects on the marine species of eastern Canada. The following table presents the main data that were used for the Scotian Shelf Bioregion assessment and identifies those that could be directly used for an update of the St. Lawrence System assessment and for a first assessment of the Newfoundland and Labrador Bioregion. It was with these realities in mind that we built this assessment using transparent and reproducible workflows that allowed for the efficient integration of new data, adjustment of certain portions of the analyses, and the production of all analyses, figures, and tables of the assessment report. It is our hope that the tools that were developed for this assessment, which lie in the realm of *data science*, could be a first step in establishing a sustainable assessment process that would seek to combine and update these assessments cyclically for a more robust and, most importantly, ***efficient***, management process of our marine ecosystems.

```{r}
rfa <- function(...) icons::fontawesome(...)
ch <- function() rfa("check")
```

<br>

| Data | Scotian Shelf | St. Lawrence | Newfoundland & Labrador |
| :----- | :---: | :---: | :---: | 
| **Biotic data** | | | |
| &nbsp;&nbsp; Marine species | `r ch()` | | |
| &nbsp;&nbsp; Marine mammals | `r ch()` | `r ch()` | `r ch()` |
| &nbsp;&nbsp; Sea birds | `r ch()` | `r ch()` | `r ch()` |
| **Abiotic data** (23) | `r ch()` | `r ch()` | `r ch()` |
| **Drivers** | | | |
| &nbsp;&nbsp; Surface-water temperature anomalies (2) | `r ch()` | `r ch()` | `r ch()` |
| &nbsp;&nbsp; Bottom-water temperature anomalies (2) | `r ch()` | | |
| &nbsp;&nbsp; Coastal development | `r ch()` | `r ch()` | `r ch()` |
| &nbsp;&nbsp; Direct human impact | `r ch()` | `r ch()` | `r ch()` |
| &nbsp;&nbsp; Inorganic pollution | `r ch()` | | |
| &nbsp;&nbsp; Organic pollution | `r ch()` | | |
| &nbsp;&nbsp; Nutrient input | `r ch()` | | |
| &nbsp;&nbsp; Population density | `r ch()` | | |
| &nbsp;&nbsp; Fisheries (5) | `r ch()` | `r ch()` | `r ch()` |
| &nbsp;&nbsp; Invasive species | `r ch()` | `r ch()` | `r ch()` |
| &nbsp;&nbsp; Shipping | `r ch()` | `r ch()` | `r ch()` |

Table: List of the main data used for the cumulative effects assessment of global changes on the ecological communities of the Scotian Shelf Bioregion and identification of their usability in the St. Lawrence System and the Newfoundland and Labrador Region.

<br>
 

## Interactive exploration of cumulative effects assessments {.unlisted .unnumbered}

As mentioned in the assessment, the results presented in the current report were limited to broad findings to simplify key takeaways. However, the approaches used allow for the exploration of all possible combinations of environmental drivers and species. Developing the tools needed for scientists and managers to explore those combinations would be highly valuable for decision-making, environmental monitoring and science planning. The [*eDrivers*](https://david-beauchesne.shinyapps.io/edriversapp_dev/) application, which now includes the Scotian Shelf Bioregion drivers characterized through this assessment, already provides the ability to explore drivers interactively; it would be valuable to expand the capabilities of *eDrivers* to include species distributions and the associated results from the cumulative effects assessment. 


## Environmental & management scenarios {.unlisted .unnumbered}

In the near future, it is expected that environmental pressures from both human and natural origins will continue to intensify globally; this suggests that we can expect emerging environmental issues to arise from this cocktail of pressures. The approaches developed by @halpern2008a and @beauchesne2020c are predictive; this means that they could be used to test scenarios of change in the distribution and intensity of environmental drivers. For instance, we could evaluate the resulting changes in cumulative effects if the intensity of fishing was to increase in certain areas of the Scotian Shelf. Similarly, management scenarios could be tested to evaluate how certain management decisions could influence cumulative risk, such as the effects of a fisheries closure in a specific portion of the Scotian Shelf. Considering the data science and reproducibility tools described above, these could be efficiently tested if management decisions must be made quickly. Testing such scenarios would allow for an analytical approach to identify proactive management and mitigation measures, which are the next steps in the cumulative effects assessment process.
